#!/usr/bin/env python3
"""Generate SQL to bulk-load the wines embedded in current-build/cwm-knowledge-base.html
into the wines/wine_grapes/wine_critic_links/wine_sources tables (0001_wines.sql).

One-time load, per README/HANDOFF: no stable product code exists in the source data,
so this does not attempt upsert/match logic. Re-running this script against a
non-empty wines table will duplicate every row. Check row counts before and after.

Usage: python3 scripts/migrate_wines.py > /tmp/wines_import.sql
"""
import json
import sys
import uuid
from pathlib import Path

HTML_PATH = Path(__file__).resolve().parent.parent / "current-build" / "cwm-knowledge-base.html"


def load_wines():
    content = HTML_PATH.read_text(encoding="utf-8")
    start = content.index("const W = ") + len("const W = ")
    wines, _ = json.JSONDecoder().raw_decode(content, start)
    return wines


def sql_str(v):
    if v is None or v == "":
        return "NULL"
    return "'" + str(v).replace("'", "''") + "'"


def sql_num(v):
    return "NULL" if v is None else str(v)


def sql_bool(v):
    return "TRUE" if v else "FALSE"


def sql_text_array(items):
    if not items:
        return "'{}'"
    escaped = ['"' + str(x).replace('"', '\\"').replace("'", "''") + '"' for x in items]
    return "'{" + ",".join(escaped) + "}'"


def main():
    wines = load_wines()
    assert len(wines) == 1513, f"expected 1513 wines, got {len(wines)} - data shape changed, re-check before importing"

    wine_rows = []
    grape_rows = []
    critic_rows = []
    source_rows = []

    for w in wines:
        wid = str(uuid.uuid4())
        o = w.get("o", {})
        stock = str(w.get("stock", "")).strip()
        nv = "NV" if w.get("nv") == "NV" else None

        wine_rows.append(
            "(" + ",".join([
                sql_str(wid),
                sql_str(w["name"]),
                sql_str(w.get("producer")),
                sql_str(w.get("category")),
                sql_str(w.get("colour")),
                sql_str(w.get("style")),
                sql_str(w.get("format")),
                sql_num(w.get("ml")),
                sql_num(w.get("vintage")),
                sql_str(nv),
                sql_num(w.get("price")),
                sql_num(w.get("was")),
                sql_num(w.get("p6")),
                sql_num(w.get("p12")),
                sql_str(stock if stock else None),
                sql_bool(w.get("inbond")),
                sql_str(w.get("dosage")),
                sql_text_array(w.get("tags")),
                sql_text_array(w.get("missing")),
                sql_num(w.get("chase")),
                sql_bool(w.get("prestige")),
                sql_str(w.get("vrow")),
                sql_str(w.get("gtier")),
                sql_str(o.get("country")),
                sql_str(o.get("region")),
                sql_str(o.get("sub")),
                sql_str(o.get("village")),
                sql_str(o.get("cl")),
                sql_str(o.get("so")),
                sql_str(w.get("desc")),
            ]) + ")"
        )

        for pos, g in enumerate(w.get("grapes", [])):
            grape_rows.append(
                "(" + ",".join([sql_str(wid), sql_str(g.get("n")), sql_num(g.get("p")), str(pos)]) + ")"
            )

        for c in w.get("clinks", []):
            critic_rows.append(
                "(" + ",".join([sql_str(wid), sql_str(c.get("n")), sql_str(c.get("u")), sql_str(c.get("note"))]) + ")"
            )

        if "src" in w:
            src = w["src"]
            source_rows.append(
                "(" + ",".join([sql_str(wid), sql_str(src.get("n")), sql_str(src.get("u")), sql_str(src.get("d"))]) + ")"
            )

    out = sys.stdout
    out.write("-- generated by scripts/migrate_wines.py, one-time load, do not re-run against a non-empty table\n\n")

    def write_insert(columns, rows):
        # an empty row list would otherwise produce "insert ... values\n;",
        # which is invalid SQL - skip the statement entirely instead.
        if not rows:
            return
        out.write(f"insert into {columns} values\n")
        out.write(",\n".join(rows) + ";\n\n")

    write_insert(
        "wines (id, name, producer, category, colour, style, format, ml, vintage, nv, "
        "price, was, price_per_6, price_per_12, stock, in_bond, dosage, tags, missing_fields, chase, "
        "prestige, vintage_chart_key, grape_tier, origin_country, origin_region, origin_sub_region, "
        "origin_village, origin_climate, origin_soil, description)",
        wine_rows,
    )
    write_insert("wine_grapes (wine_id, grape_name, percentage, position)", grape_rows)
    write_insert("wine_critic_links (wine_id, critic_name, search_url, usage_note)", critic_rows)
    write_insert("wine_sources (wine_id, source_name, source_url, date_checked)", source_rows)

    print(
        f"-- {len(wine_rows)} wines, {len(grape_rows)} grapes, {len(critic_rows)} critic links, "
        f"{len(source_rows)} sources",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
